### ISSUE TITLE
Support for astral characters (like emoji)

### ISSUE THREAD

**Issue by lewisje** [chatty/chatty#48] opened 2016-04-21 01:42 UTC
I realize that Java treats strings as UTF-16, so this won't be easy, but it would be nice to render emojis and use the platform's emoji fallback font, if one exists.

**Comment by tduva** [comment] 2016-04-21 09:18
What does UTF-16 have to do with it? It's just the representation of Unicode that Java uses internally, it shouldn't cause any issues.

The problem is the fallback font. The one that is contained in Java doesn't display all characters and adding one programmatically doesn't seem to be possible. You have to put the font into the right JRE directory (`<JRE_INSTALL_DIR>/jre/lib/fonts/fallback`), which ususally requires admin rights.

**Comment by lewisje** [comment] 2016-04-21 18:43
I thought maybe the program had a problem with surrogate pairs, I know Javascript programs (which uses either UCS-2 or UTF-16) frequently do.

I looked up the problem of fallback fonts in Java, and it looks like you could kludgily specify a wide variety of common emoji fonts as fallbacks: http://stackoverflow.com/a/9482676/3135268

This particular solution would need to be extended to try out a variety of fallbacks, and I can imagine it being slow; I also don't know whether it's possible to refer to a font in the same directory as the JAR file, or inside of it (although you seemed to indicate that it's not), but if it is, Symbola is free for personal use and for distribution.

Anyway, I tried adding an emoji font to the `lib/fonts/fallback` subdirectory of my JRE (and I had to create the fallback directory), and when I re-launched Chatty again, emojis worked; I now recommend that you should tell other Chatty users about this workaround on the front page, something like "Download Symbola, make a 'fallback' directory in your 'lib/fonts' directory in your JRE if you don't have such a directory, and copy Symbola_hint.ttf to it."

**Comment by lewisje** [comment] 2016-06-28 23:08
As an update for the Unicode 9.0 emojis, because it looks like Symbola won't be updated, additionally add this font based on the EmojiOne set, which does include black-and-white glyphs in addition to color: https://github.com/eosrei/emojione-color-font

**Comment by tduva** [comment] 2016-07-06 09:49
I'm in the process of adding support for Emoji (turn them into an image like emotes). Although the fallback font could probably still be useful, for example for entering Emoji, since there are no images in the input box. I don't think the Twitter Emoji I'm using actually support Unicode 9.0 though. Maybe I could supplement those from another set. Either way, if this works out it should be an improvement.

**Comment by GhettoGirl** [comment] 2016-07-06 14:48
@tduva How about [Apple's](http://emojipedia.org/apple/) emote set? Or even better, let the user select between emote sets. The filename of the image is the codepoint.

Example: :grin: is ```U+1F601``` so the filename would be ```1f601.png``` or ```1f601.svg```. PNG vs SVG depending on the details of the emote in the corresponding emote set.

**Comment by tduva** [comment] 2016-07-20 03:29
I prefer the Twitter Emoji, so at most I'd add support for different sets. Since you mentioned Apple Emoji, is there an official source for the image files? I couldn't find any.

**Comment by lewisje** [comment] 2016-07-20 03:40
The Apple emoji images are not freely available; the only freely available sources of emoji images that I am aware of that go up to Unicode 9.0 are Twemoji and EmojiOne (not sure whether Google Noto Emoji has updated to that yet).

Also, it turns out that Symbola actually was just updated to Unicode 9.0, and that's superior to both the EmojiOne and Twemoji fonts when dealing strictly with black-and-white input, both because it is much smaller (because it doesn't have any color data) and because its black-and-white symbols actually look better than the black-and-white versions of EmojiOne and Twemoji.

**Comment by GhettoGirl** [comment] 2016-08-10 16:44
Support for emojis was added here 5e753d974c2fb0fe6e52b70f7f06f2d345b9b046.
In my fork I added the Apple emoticons, because I prefer it over the other 2 sets, GhettoGirl/chatty@bdb2b177dd13f48f7c0000305d834285a165f250. The set is incomplete (missing emotes was merged from Twitter), but the most common emotes are there and they look great. :grin:

**Closed** 2016-10-02 05:03 UTC
