### ISSUE TITLE
java.lang.NullPointerException in FFZ Emote handling

### ISSUE THREAD

**Issue by dracool** [chatty/chatty#103] opened 2016-10-28 17:17 UTC
This Exception happens multiple times a day for exactly this emote. I suspect it didn't exist before the resize but it tries to remove it now.
```
Error Report // Chatty Version 0.8.4 Hotkey / JDK8 / Java: 1.8.0_111 (Oracle Corporation) OS: Windows 10 (10.0/amd64) / [Memory] total: 296.960 used: 239.425 free: 57.534 max: 7.440.384 [Uptime] 4d 12h 0m 0s

07:13:49 [FFZ] Request: https://api.frankerfacez.com/v1/set/22546
07:13:49 [FFZ] Response (200, 5440, gzip): https://api.frankerfacez.com/v1/set/22546
07:13:49 Changed 'BloodTrailWeen'/FFZ emote size: 180x32 -> 100x17
07:13:49 [FFZ] (22546, global): 17 emotes received.
07:13:49 Unhandled Exception:
java.lang.NullPointerException
	at chatty.util.api.Emoticons.removeEmoticons(Emoticons.java:173)
	at chatty.util.api.Emoticons.updateEmoticons(Emoticons.java:143)
	at chatty.gui.MainGui$82.run(MainGui.java:3352)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by GhettoGirl** [comment] 2016-10-28 17:58
duplicate of #102 (literally the first issue in the list before you created this one)

**Comment by dracool** [comment] 2016-10-29 12:50
Oh, didn't see, tho maybe a better title than "java.security.AccessController.doPrivileged" is useful? I looked over the issue titles and that didn't even strike me as possibly being the same as this one.

**Closed** 2016-10-29 12:50 UTC
