### ISSUE TITLE
Animated emotes causing huge cpu usage spikes

### ISSUE THREAD

**Issue by ipangrazio** [chatty/chatty#20] opened 2015-09-28 17:52 UTC
Whenever somebody in a chat uses the emotes KKonaPls or Citto, my cpu usage spikes to ~50-80%, which is extremely detrimental to the performance of all other applications. It also continues to stay at about 25-50% usage after closing the channel that the emote was displayed in (but not closing the program).

Screenshots:
![screenshot 14](https://cloud.githubusercontent.com/assets/14877035/10143773/09fe9046-65e8-11e5-9af9-ac0f0c4e0ada.png)
![screenshot 15](https://cloud.githubusercontent.com/assets/14877035/10143774/0a0aa8ae-65e8-11e5-842b-a7b620be5556.png)

**Comment by tduva** [comment] 2015-10-08 14:11
This is caused by the animated GIFs having a delay of 0 between frames. I'm not sure if this is strictly valid for a GIF, but in any case Java doesn't handle it very well. Browsers and other programs seem to slow it down to some default value.

**Comment by tduva** [comment] 2015-10-09 12:15
The latest beta [v0.8.2b3](https://github.com/chatty/chatty/releases/tag/v0.8.2b3) has an experimental fix for this.

**Closed** 2016-10-02 05:04 UTC
Labels: bug
